### ISSUE TITLE
Running with scala 2.10 for version 3.3.0 does not work due to java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by arun936** [scopt/scopt#77]
Here is the error message:

```
Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.IntRef.create(I)Lscala/runtime/IntRef;
    at scopt.OptionParser.parse(options.scala:322)
        ...
```

I am running with Scala 2.10.4. scopt works with Scala 2.11.7. However, I need to use with Scala 2.10.4 because I am using other packages that require 2.10.4. I am building using scala 2.10.4.

Please let me know what I should try/change.

Thanks.

**Comment by eed3si9n** [comment]
Do you have repro steps or project that I can look at?

**Comment by arun936** [comment]
My bad. Even thought that I had it all nailed down, there was still one place where scala 2.11 was being used for building the jar. When I corrected that to consistently use scala 2.10, it all worked fine.

Thanks for the quick response!
